<?php
/**
 * Created by PhpStorm.
 * User: helei
 * Date: 16/7/31
 * Time: 上午9:20
 */

namespace Payment\Common\Weixin\Data\Charge;


use Payment\Common\PayException;
use Payment\Utils\ArrayUtil;

/**
 * Class PubChargeData
 * 微信公众号支付
 *
 * @package Payment\Common\Weixin\Data\Charge
 * anthor helei
 */
class PubChargeData extends ChargeBaseData
{

    protected function checkDataParam()
    {
        parent::checkDataParam(); // TODO: Change the autogenerated stub

        // 公众号支付,必须设置openid
        $openid = $this->openid;
        if (empty($openid)) {
            throw new PayException('用户在商户appid下的唯一标识,公众号支付,必须设置该参数.');
        }
    }

    protected function buildData()
    {
        $signData = [
            // 基本数据
            'appid' => trim($this->appId),
            'mch_id'    => trim($this->mchId),
            'device_info'   => 'WEB',
            'nonce_str' => $this->nonceStr,
            'fee_type'  => $this->feeType,
            'notify_url'    => $this->notifyUrl,
            'time_start'    => $this->timeStart,
            'time_expire'   => $this->timeExpire,
            //'limit_pay' => 'no_credit',  // 指定不使用信用卡

            // 业务数据
            'body'  => trim($this->body),
            'attach'    => trim($this->extra_param),
            'out_trade_no'  => trim($this->order_no),
            'total_fee' => $this->amount,
            'spbill_create_ip'  => trim($this->client_ip),
            'trade_type'    => 'JSAPI', //设置公众号支付
            'openid'    => $this->openid,// trade_type=JSAPI，此参数必传，用户在商户appid下的唯一标识
        ];

        // 移除数组中的空值
        $this->retData = ArrayUtil::paraFilter($signData);
    }
}