<?php
/**
 * Created by PhpStorm.
 * User: helei
 * Date: 16/7/31
 * Time: 上午8:49
 */

namespace Payment\Common\Weixin\Data\Charge;

use Payment\Common\PayException;
use Payment\Utils\ArrayUtil;


/**
 * Class WebChargeData
 *
 * @inheritdoc
 *
 * @package Payment\Common\Weixin\Data\Charge
 */
class QrChargeData extends ChargeBaseData
{

    /**
     * 生成下单的数据
     * @return array
     */
    protected function buildData()
    {
        $signData = [
            // 基本数据
            'appid' => trim($this->appId),
            'mch_id'    => trim($this->mchId),
            'device_info'   => 'WEB',
            'nonce_str' => $this->nonceStr,
            'fee_type'  => $this->feeType,
            'notify_url'    => $this->notifyUrl,
            'time_start'    => $this->timeStart,
            'time_expire'   => $this->timeExpire,
            //'limit_pay' => 'no_credit',  // 指定不使用信用卡

            // 业务数据
            'body'  => trim($this->body),
            'attach'    => trim($this->extra_param),
            'out_trade_no'  => trim($this->order_no),
            'total_fee' => $this->amount,
            'spbill_create_ip'  => trim($this->client_ip),
            'trade_type'    => 'NATIVE', //设置扫码支付
            'product_id'    => $this->product_id,
        ];

        // 移除数组中的空值
        $this->retData = ArrayUtil::paraFilter($signData);
    }

    protected function checkDataParam()
    {
        parent::checkDataParam(); // TODO: Change the autogenerated stub

        // 扫码支付,必须设置product_id  参数
        $productId = $this->product_id;
        if (empty($productId)) {
            throw new PayException('扫码支付,必须设置商品ID.');
        }
    }
}