<?php
/**
 * @author: helei
 * @createTime: 2016-07-28 17:23
 * @description: 支付宝订单查询接口
 */

namespace Payment\Query;


use Payment\Common\Ali\AliBaseStrategy;
use Payment\Common\Ali\Data\BaseData;
use Payment\Common\Ali\Data\TradeQueryData;
use Payment\Common\PayException;
use Payment\Config;
use Payment\Utils\ArrayUtil;
use Payment\Utils\Curl;
use Payment\Utils\DataParser;

class AliTradeQuery extends AliBaseStrategy
{

    protected function getBuildDataClass()
    {
        return TradeQueryData::class;
    }
    
    protected function retData(array $data)
    {
        $url = parent::retData($data); // TODO: Change the autogenerated stub

        $ret = $this->request($url);

        return $this->createBackData($ret);
    }

    /**
     * 进行网络请求，获取订单查询结果
     * @param string $url
     * @return array
     *
     * ```php
     * $data =[
     *  'subject'   => 'subject', //
     *  'body'   => 'body',
     *  'amount'   => $'total_fee',
     *  'channel'   => Config::ALI,
     *  'order_no'   => 'out_trade_no',
     *  'buyer_id'   => 'buyer_email',
     *  'trade_state'   => $status,
     *  'transaction_id'   => 'trade_no',
     *  'time_end'   => 'gmt_payment',
     * ]
     * ```
     *
     * @throws PayException
     * @author helei
     */
    protected function request($url)
    {
        // 发起网络请求
        $curl = new Curl();
        $responseTxt = $curl->set([
            'CURLOPT_SSL_VERIFYPEER'    => true,
            'CURLOPT_SSL_VERIFYHOST'    => 2,
            'CURLOPT_CAINFO'    => $this->config->cacertPath,
            'CURLOPT_HEADER'    => 0,// 为了便于解析，将头信息过滤掉
        ])->get($url);

        if ($responseTxt['error']) {
            throw new PayException('网络发生错误，请稍后再试');
        }

        // 格式化为数组
        $retData = DataParser::toArray($responseTxt['body']);

        // 移除不必要参数
        $retData = ArrayUtil::removeKeys($retData, ['sign', 'sign_type', 'request']);
        $retData['response'] = $retData['response']['trade'];

        return $retData;
    }

    /**
     * 处理支付宝返回的数据，统一处理后返回
     * @param array $data  支付宝返回的数据
     * @return array
     * @author helei
     */
    protected function createBackData(array $data)
    {
        if ($data['is_success'] === 'F') {
            return $retData = [
                'is_success'    => 'F',
                'error' => $data['error']
            ];
        }

        // 正确情况
        $retData = [
            'is_success'    => 'T',
            'response'  => [
                'subject'   => $data['response']['subject'],
                'body'   => isset($data['response']['body']) ? $data['response']['body'] : '',
                'amount'   => $data['response']['total_fee'],
                'channel'   => Config::ALI,
                'order_no'   => $data['response']['out_trade_no'],
                'buyer_id'   => $data['response']['buyer_email'],
                'trade_state'   => $data['response']['trade_status'],
                'transaction_id'   => $data['response']['trade_no'],
                'time_end'   => $data['response']['gmt_payment'],
            ],
        ];

        return $retData;
    }
}